included:
    - GitHubSearch-2

excluded:
    - GitHubSearch-2Tests
    - GitHubSearch-2UITests

disabled_rules:
  - trailing_whitespace
  - function_body_length
  - colon
  - comma
  - control_statement
  - todo
  - function_parameter_count
  - type_body_length
  - cyclomatic_complexity
  - identifier_name
  - nesting
  - notification_center_detachment
  - file_length
  - large_tuple

opt_in_rules:
    - conditional_returns_on_newline
    - shorthand_optional_binding
    - implicit_return

line_length: 250

type_name:
    max_length: 50

file_length:
  warning: 500
  error: 2500

identifier_name:
  min_length: 2
    error: 4
  excluded: 
    - id
    - URL
    - GlobalAPIKey
