included:
    - GitHubSearch-2

excluded:
    - GitHubSearch-2Tests
    - GitHubSearch-2UITests

disabled_rules:
  - trailing_whitespace
  - function_body_length
  - colon
  - comma
  - control_statement
  - todo
  - function_parameter_count
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - notification_center_detachment
  - large_tuple
  - identifier_name

opt_in_rules:
    - conditional_returns_on_newline
    - shorthand_optional_binding
    - implicit_return

line_length:
  warning: 180
  error: 240
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 2500
